import logging
import time
from typing import Any, Dict, Optional, Type
from pydantic import BaseModel
from openai import OpenAI
import openai

from app.core.config import settings

logger = logging.getLogger(__name__)


class LLMTimeoutError(Exception):
    pass


class LLMRateLimitError(Exception):
    pass


class LLMServiceError(Exception):
    pass


def with_retry(max_retries=3, initial_backoff=1.0):
    def decorator(func):
        def wrapper(*args, **kwargs):
            backoff = initial_backoff
            for attempt in range(max_retries):
                try:
                    return func(*args, **kwargs)
                except openai.APITimeoutError as e:
                    if attempt == max_retries - 1:
                        raise LLMTimeoutError(f"LLM request timed out after {max_retries} attempts: {e}")
                    logger.warning(f"Timeout on attempt {attempt+1}, retrying in {backoff}s...")
                except openai.RateLimitError as e:
                    if attempt == max_retries - 1:
                        raise LLMRateLimitError(f"LLM rate limited after {max_retries} attempts: {e}")
                    logger.warning(f"Rate limit on attempt {attempt+1}, retrying in {backoff}s...")
                except openai.APIError as e:
                    raise LLMServiceError(f"LLM API error: {e}")
                time.sleep(backoff)
                backoff *= 2
        return wrapper
    return decorator


class LLMClient:
    def __init__(self):
        self.api_key = settings.OPENAI_API_KEY or "ollama-local"
        self.model = settings.LLM_MODEL
        self.base_url = (
            settings.OLLAMA_BASE_URL if not settings.OPENAI_API_KEY else None
        )
        self._client: Optional[OpenAI] = None

    @property
    def client(self) -> OpenAI:
        if not self._client:
            kwargs = {"api_key": self.api_key}
            if self.base_url:
                kwargs["base_url"] = self.base_url
            self._client = OpenAI(**kwargs)
        return self._client

    @with_retry(max_retries=3)
    def generate_completion(
        self,
        system_prompt: str,
        user_prompt: str,
        temperature: float = 0.1,
        json_mode: bool = False,
        timeout: Optional[float] = None,
        trace_id: Optional[str] = None,
        model: Optional[str] = None,
        max_tokens: Optional[int] = None,
    ) -> str:
        start_time = time.time()
        actual_timeout = timeout or settings.LLM_TIMEOUT_SECONDS
        target_model = model or self.model
        kwargs = {
            "model": target_model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            "temperature": temperature,
            "timeout": actual_timeout,
        }

        if max_tokens:
            kwargs["max_tokens"] = max_tokens

        if json_mode and not self.base_url:
            kwargs["response_format"] = {"type": "json_object"}

        response = self.client.chat.completions.create(**kwargs)
        
        duration = time.time() - start_time
        tokens = response.usage.total_tokens if response.usage else 0
        if trace_id:
            logger.info(f"[TRACE: {trace_id}] generate_completion: {duration:.2f}s, {tokens} tokens, model={self.model}")

        return response.choices[0].message.content

    def generate_stream(
        self,
        system_prompt: str,
        user_prompt: str,
        temperature: float = 0.1,
        timeout: Optional[float] = None,
    ):
        """
        Yields text tokens as they are generated by the LLM.
        """
        actual_timeout = timeout or settings.LLM_TIMEOUT_SECONDS
        kwargs = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            "temperature": temperature,
            "timeout": actual_timeout,
            "stream": True,
        }

        try:
            response = self.client.chat.completions.create(**kwargs)
            for chunk in response:
                if chunk.choices and len(chunk.choices) > 0:
                    delta = chunk.choices[0].delta
                    if delta and delta.content:
                        yield delta.content
        except Exception as e:
            logger.exception("Error during LLM streaming")
            yield f"\n\n[Error during LLM generation: {str(e)}]"

    @with_retry(max_retries=3)
    def generate_parsed_completion(
        self,
        system_prompt: str,
        user_prompt: str,
        response_format: Type[BaseModel],
        temperature: float = 0.0,
        timeout: Optional[float] = None,
        trace_id: Optional[str] = None,
        model: Optional[str] = None,
        max_tokens: Optional[int] = None,
    ) -> BaseModel:
        start_time = time.time()
        actual_timeout = timeout or settings.LLM_TIMEOUT_SECONDS
        
        # Fallback for local models that don't support native structured beta parse
        if self.base_url:
            raw = self.generate_completion(
                system_prompt, 
                user_prompt, 
                temperature=temperature, 
                timeout=actual_timeout,
                trace_id=trace_id,
                model=model,
                max_tokens=max_tokens,
            )
            import json

            # Clean markdown code blocks if any
            clean_raw = raw.strip()
            if clean_raw.startswith("```"):
                clean_raw = clean_raw.split("```")[1]
                if clean_raw.startswith("json"):
                    clean_raw = clean_raw[4:]
            data = json.loads(clean_raw)
            return response_format(**data)

        response = self.client.beta.chat.completions.parse(
            model=self.model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            response_format=response_format,
            temperature=temperature,
            timeout=actual_timeout,
        )
        
        duration = time.time() - start_time
        tokens = response.usage.total_tokens if response.usage else 0
        if trace_id:
            logger.info(f"[TRACE: {trace_id}] generate_parsed_completion: {duration:.2f}s, {tokens} tokens, model={self.model}")
            
        return response.choices[0].message.parsed


llm_client = LLMClient()
