"""
Index Sync Repository
=====================

This module manages the synchronization state between the PostgreSQL source of truth
and the Qdrant vector database.

Key Responsibilities:
  1. DDL Provisioning: Safely checks and creates the `ai_semantic_documents` and 
     `ai_vector_index_status` tracking tables on startup.
  2. Sync Tracking: Records exactly when a script was last embedded, allowing the 
     IndexingService to skip unmodified scripts (delta synchronization).
  3. Caching: Caches the heavy LLM-generated markdown documents in PostgreSQL so they
     do not need to be regenerated if Qdrant is wiped.
"""

import logging
import uuid
from typing import Any

from sqlalchemy import text

from app.core.config import settings
from app.repositories.db import engine

# ── logger initialization ───────────────────────────────────────────────
logger = logging.getLogger(__name__)


# ── class definition ──────────────────────────────────────────────────
class IndexRepository:
    """
    Data Access Object (DAO) for tracking semantic embedding state and sync status.
    """

    def __init__(self):
        self._ensure_ai_tables()

    # ── table provisioning ──────────────────────────────────────────────
    def _ensure_ai_tables(self):
        """
        Ensures AI-owned tables exist in PostgreSQL per Section 29 guardrails.
        Executes gracefully, ignoring errors if DDL permissions are restricted in production.
        """
        try:
            with engine.connect() as conn:
                conn.execute(
                    text(
                        """
                    CREATE TABLE IF NOT EXISTS ai_semantic_documents (
                        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                        test_script_id UUID NOT NULL,
                        semantic_document TEXT NOT NULL,
                        generated_by VARCHAR(50) DEFAULT 'llm',
                        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
                    )
                """
                    )
                )
                conn.execute(
                    text(
                        """
                    CREATE TABLE IF NOT EXISTS ai_vector_index_status (
                        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                        test_script_id UUID NOT NULL,
                        embedding_model VARCHAR(100) NOT NULL,
                        dimension INT NOT NULL,
                        indexed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
                    )
                """
                    )
                )
                conn.commit()
        except Exception as exc:
            logger.debug(
                "Could not auto-create AI tables (might already exist or lack DDL perms): %s",
                exc,
            )

    # ── semantic caching ────────────────────────────────────────────────
    def record_semantic_document(
        self, script_id: str, document: str, generated_by: str = "llm"
    ):
        """
        Saves the markdown document generated by the LLM into PostgreSQL for caching.
        """
        self._ensure_ai_tables()
        try:
            with engine.connect() as conn:
                conn.execute(
                    text(
                        """
                        INSERT INTO ai_semantic_documents (id, test_script_id, semantic_document, generated_by)
                        VALUES (CAST(:id AS UUID), CAST(:script_id AS UUID), :document, :generated_by)
                    """
                    ),
                    {
                        "id": str(uuid.uuid4()),
                        "script_id": str(script_id),
                        "document": document,
                        "generated_by": generated_by,
                    },
                )
                conn.commit()
        except Exception as exc:
            logger.warning(
                "Failed to record semantic document in ai_semantic_documents: %s", exc
            )

    def get_semantic_document(self, script_id: str) -> dict | None:
        """
        Retrieves the most recently generated semantic document for a given script.
        """
        self._ensure_ai_tables()
        try:
            with engine.connect() as conn:
                res = conn.execute(
                    text(
                        "SELECT semantic_document, generated_by FROM ai_semantic_documents WHERE test_script_id = CAST(:script_id AS UUID) ORDER BY created_at DESC LIMIT 1"
                    ),
                    {"script_id": str(script_id)},
                )
                row = res.first()
                if row:
                    return {
                        "semantic_document": row[0],
                        "generated_by": row[1],
                    }
                return None
        except Exception as exc:
            logger.warning("Failed to retrieve semantic document: %s", exc)
            return None

    # ── sync status tracking ────────────────────────────────────────────
    def record_index_status(self, script_id: str, model_name: str, dimension: int):
        """
        Records the successful vector embedding of a script, linking it to the specific model version used.
        """
        self._ensure_ai_tables()
        try:
            with engine.connect() as conn:
                conn.execute(
                    text(
                        """
                        INSERT INTO ai_vector_index_status (id, test_script_id, embedding_model, dimension)
                        VALUES (CAST(:id AS UUID), CAST(:script_id AS UUID), :model_name, :dimension)
                    """
                    ),
                    {
                        "id": str(uuid.uuid4()),
                        "script_id": str(script_id),
                        "model_name": model_name,
                        "dimension": dimension,
                    },
                )
                conn.commit()
        except Exception as exc:
            logger.warning(
                "Failed to record index status in ai_vector_index_status: %s", exc
            )

    def record_batch_index_status(self, records: list[dict[str, Any]]):
        """
        Records the successful indexing of a batch of scripts in a single database transaction.
        
        Args:
            records (List[Dict]): List of dicts with keys: script_id, document, generated_by, model_name, dimension.
        """
        if not records:
            return
        self._ensure_ai_tables()
        try:
            with engine.connect() as conn:
                doc_params = [
                    {
                        "id": str(uuid.uuid4()),
                        "script_id": str(r["script_id"]),
                        "document": r["document"],
                        "generated_by": r.get("generated_by", "deterministic_fallback"),
                    }
                    for r in records
                ]
                status_params = [
                    {
                        "id": str(uuid.uuid4()),
                        "script_id": str(r["script_id"]),
                        "model_name": r.get("model_name", settings.EMBEDDING_MODEL_NAME),
                        "dimension": r.get("dimension", settings.EMBEDDING_DIMENSION),
                    }
                    for r in records
                ]
                
                conn.execute(
                    text(
                        """
                        INSERT INTO ai_semantic_documents (id, test_script_id, semantic_document, generated_by)
                        VALUES (CAST(:id AS UUID), CAST(:script_id AS UUID), :document, :generated_by)
                        """
                    ),
                    doc_params,
                )
                conn.execute(
                    text(
                        """
                        INSERT INTO ai_vector_index_status (id, test_script_id, embedding_model, dimension)
                        VALUES (CAST(:id AS UUID), CAST(:script_id AS UUID), :model_name, :dimension)
                        """
                    ),
                    status_params,
                )
                conn.commit()
        except Exception as exc:
            logger.warning("Failed to record batch index status in PostgreSQL: %s", exc)

    def list_all_script_ids(self) -> list[str]:
        """
        Retrieves all active script IDs from the master table for bulk indexing.
        """
        try:
            with engine.connect() as conn:
                res = conn.execute(text("SELECT test_script_id FROM test_scripts"))
                return [str(row[0]) for row in res.all()]
        except Exception as exc:
            logger.error("Failed to list script ids: %s", exc)
            return []

    def list_stale_script_ids(self) -> list[str]:
        """
        Retrieves scripts that have not been indexed yet, or were indexed by an older model.
        (Currently aliases list_all_script_ids until delta logic is required).
        """
        return self.list_all_script_ids()


# ── singleton export ──────────────────────────────────────────────────
index_repository = IndexRepository()
